basePath: /
host: exclusivestore.xyz
info:
  contact: {}
  description: SOCIAL MATCH API Gateway server.
  termsOfService: http://swagger.io/terms/
  title: Social-Match
  version: "1.0"
paths: {}
securityDefinitions:
  AdminAutherisation:
    in: header
    name: AccessToken
    type: apiKey
  UserAuthorization:
    in: header
    name: AccessToken
    type: apiKey
  UserConfirmToken:
    in: header
    name: ConfirmToken
    type: apiKey
swagger: "2.0"
