apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-service-config
  namespace: socialmatch
data:
  PORT: ":50052"
  DB_HOST: socialmatch-postgres
  DB_NAME: admin_svc
  DB_USER: postgres
  DB_PASSWORD: "8596"
  DB_PORT: "5432"
  CHAT_SVC_URL: "socialmatch-user-service.socialmatch.svc.cluster.local:8001"
  USER_SVC_URL: "socialmatch-user-service.socialmatch.svc.cluster.local:8002"
  ADMIN_SVC_URL: "socialmatch-admin-service.socialmatch.svc.cluster.local:8003"
  ROOM_SVC_URL: "socialmatch-room-service.socialmatch.svc.cluster.local:8004"
  CONNECTION_SVC_URL: "socialmatch-connections-service.socialmatch.svc.cluster.local:8005"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialmatch-admin-svc
  namespace: socialmatch
spec:
  selector:
    matchLabels:
      app: admin_service
  template:
    metadata:
      labels:
        app: admin_service
    spec:
      containers:
        - image: bibinzoz/socialmatch-admin-service:latest
          imagePullPolicy: Always
          name: social-match-admin-service-container
          ports:
            - containerPort: 50052
          envFrom:
            - configMapRef:
                name: admin-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: socialmatch-admin-service
  namespace: socialmatch
spec:
  type: ClusterIP
  ports:
    - port: 8003
      targetPort: 50052
  selector:
    app: admin_service

