apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: socialmatch
data:
  PORT: ":3000"
  CHAT_SVC_URL: "socialmatch-user-service.socialmatch.svc.cluster.local:8001"
  USER_SVC_URL: "socialmatch-user-service.socialmatch.svc.cluster.local:8002"

  ADMIN_SVC_URL: "socialmatch-admin-service.socialmatch.svc.cluster.local:8003"
  ROOM_SVC_URL: "socialmatch-room-service.socialmatch.svc.cluster.local:8004"
  CONNECTION_SVC_URL: "socialmatch-connections-service.socialmatch.svc.cluster.local:8005"
