apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letencrypt-cluster-issuer
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    email: bibinvinodvfx@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    solvers:
    - http01:
        ingress:
          class: nginx
