// interest.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: pkg/pb/interest/interest.proto

package interest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	InterestService_CheckInterest_FullMethodName = "/InterestService/CheckInterest"
)

// InterestServiceClient is the client API for InterestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InterestServiceClient interface {
	CheckInterest(ctx context.Context, in *CheckInterestRequest, opts ...grpc.CallOption) (*CheckInterestResponse, error)
}

type interestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInterestServiceClient(cc grpc.ClientConnInterface) InterestServiceClient {
	return &interestServiceClient{cc}
}

func (c *interestServiceClient) CheckInterest(ctx context.Context, in *CheckInterestRequest, opts ...grpc.CallOption) (*CheckInterestResponse, error) {
	out := new(CheckInterestResponse)
	err := c.cc.Invoke(ctx, InterestService_CheckInterest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterestServiceServer is the server API for InterestService service.
// All implementations must embed UnimplementedInterestServiceServer
// for forward compatibility
type InterestServiceServer interface {
	CheckInterest(context.Context, *CheckInterestRequest) (*CheckInterestResponse, error)
	mustEmbedUnimplementedInterestServiceServer()
}

// UnimplementedInterestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInterestServiceServer struct {
}

func (UnimplementedInterestServiceServer) CheckInterest(context.Context, *CheckInterestRequest) (*CheckInterestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckInterest not implemented")
}
func (UnimplementedInterestServiceServer) mustEmbedUnimplementedInterestServiceServer() {}

// UnsafeInterestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterestServiceServer will
// result in compilation errors.
type UnsafeInterestServiceServer interface {
	mustEmbedUnimplementedInterestServiceServer()
}

func RegisterInterestServiceServer(s grpc.ServiceRegistrar, srv InterestServiceServer) {
	s.RegisterService(&InterestService_ServiceDesc, srv)
}

func _InterestService_CheckInterest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInterestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterestServiceServer).CheckInterest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterestService_CheckInterest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterestServiceServer).CheckInterest(ctx, req.(*CheckInterestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InterestService_ServiceDesc is the grpc.ServiceDesc for InterestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InterestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "InterestService",
	HandlerType: (*InterestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckInterest",
			Handler:    _InterestService_CheckInterest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/interest/interest.proto",
}
