name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: gcr.io

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/your-project-id/socialmatch-api-gateway:latest .
          docker push gcr.io/your-project-id/socialmatch-api-gateway:latest

      - name: Configure Google Cloud CLI
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: noted-hangout-424114-t9
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials social-match --zone us-central1-c --project noted-hangout-424114-t9
          kubectl apply -f deployment/api-gateway-k8s.yaml
