name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t bibinzoz/socialmatch-api-gateway:latest .
          docker push bibinzoz/socialmatch-api-gateway:latest

      # Decode service account key and save it to a file
      - name: Decode service account key
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > /tmp/gcp-sa-key.json

      # Authenticate with Google Cloud using service account key
      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=/tmp/gcp-sa-key.json
          gcloud config set project noted-hangout-424114-t9  # Replace with your actual project ID
          gcloud container clusters get-credentials social-match --zone us-central1-c

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials social-match --zone us-central1-c --project noted-hangout-424114-t9
          kubectl apply -f deployment/api-gateway-k8s.yaml
