name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker compose -f docker-compose.yaml build
        docker images
        docker tag socialmatch-microservice-api-gateway bibinzoz/socialmatch-api-gateway:latest
        docker tag socialmatch-microservice-user-service bibinzoz/socialmatch-user-service:latest
        docker tag socialmatch-microservice-admin-service bibinzoz/socialmatch-admin-service:latest
        docker tag socialmatch-microservice-connections-service bibinzoz/socialmatch-connections-service:latest
        docker tag socialmatch-microservice-chat-service bibinzoz/socialmatch-chat-service:latest
        docker tag socialmatch-microservice-room-service bibinzoz/socialmatch-room-service:latest
        docker push bibinzoz/socialmatch-api-gateway:latest
        docker push bibinzoz/socialmatch-user-service:latest
        docker push bibinzoz/socialmatch-admin-service:latest
        docker push bibinzoz/socialmatch-connections-service:latest
        docker push bibinzoz/socialmatch-chat-service:latest
        docker push bibinzoz/socialmatch-room-service:latest

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Add Google Cloud SDK repository
      run: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        sudo apt-get install apt-transport-https ca-certificates gnupg
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt-get update
    
    - name: Install gke-gcloud-auth-plugin 
      run: |
        sudo apt-get update
        sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials socialmatch --zone us-central1-c --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Update Kubernetes deployments
      run: |
        kubectl delete -f deployment/api-gateway-k8s.yaml
        kubectl apply -f deployment/api-gateway-k8s.yaml
        # kubectl apply -f deployment/user-service-k8s.yaml
        kubectl apply -f deployment/admin-service-k8s.yaml
        kubectl apply -f deployment/chat-service-k8s.yaml
        kubectl apply -f deployment/connections-service-k8s.yaml
        kubectl apply -f deployment/room-service-k8s.yaml
